mod exploit;

#[tokio::main]
async fn main() {
    if let Err(e) = exploit::run().await {
        println!("[-] Error: {}", e)
    }
}
